---
  - name: Install MySQL Server and its Python module for Ansible communication
    apt: pkg="{{item}}" update_cache=yes
    with_items:
      - mysql-server
      - python-mysqldb

  - name: Bind MySQL to 0.0.0.0
    lineinfile: 'dest=/etc/mysql/my.cnf regexp=^bind\-address line="bind-address = 0.0.0.0"'
    notify:
      - Restart MySQL
